package byow.Core;

import byow.TileEngine.TERenderer;
import byow.TileEngine.TETile;

import java.util.Random;

/**
 * A minimal demo that renders a world generated by {@link WorldGenerator}.
 * Each run uses a random seed, so the world differs every time.
 */
public class Demo {

    private static final int WIDTH = 120;
    private static final int HEIGHT = 80;

    public static void main(String[] args) {
        TERenderer ter = new TERenderer();
        ter.initialize(WIDTH, HEIGHT);

        long seed = new Random().nextLong();
        TETile[][] world = WorldGenerator.generateWorld(WIDTH, HEIGHT, seed);

        ter.renderFrame(world);
    }
}
