package byow.Core;

import byow.TileEngine.TERenderer;
import byow.TileEngine.TETile;

import java.util.Random;

/**
 * A minimal demo that renders a world generated by {@link WorldGenerator}.
 * Each run uses a random seed, so the world differs every time.
 */
public class Demo {

    private static final int WIDTH = 80;
    private static final int HEIGHT = 40;

    public static void main(String[] args) {
        Engine engine = new Engine();
        TERenderer ter = new TERenderer();
        ter.initialize(WIDTH, HEIGHT);

        long seed = new Random().nextLong();
        TETile[][] world = engine.interactWithInputString("n5197880843569031643s");
        //TETile[][] world = engine.interactWithInputString("n12345s");

        ter.renderFrame(world);
    }
}
